version: "3"
networks:
    postgresnet:

services:
    server:
        image: shop
        build: .
        restart: always
        container_name: shop
        depends_on:
            - postgresql
        ports:
            - "5000:5000"
        networks:
            - postgresnet
        links:
            - postgresql

    postgresql:
        image: postgres
        hostname: postgresql
        container_name: postgresql
        restart: always
        environment:
            - DBUSER=postgre
            - DBPASS=postgre
            - DBNAME=honeybunny
        ports:
            - "5432:5432"
        networks:
            - postgresnet
