"""empty message

Revision ID: 550f90e9d49d
Revises: 930a2dd9a6e7
Create Date: 2020-03-02 22:46:59.056025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f90e9d49d'
down_revision = '930a2dd9a6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_good', 'Busket', ['user_id', 'good_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_good', 'Busket', type_='unique')
    # ### end Alembic commands ###
