"""empty message

Revision ID: 6495dc8697b9
Revises: ce8f2c2b92c4
Create Date: 2020-03-02 21:28:11.007835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6495dc8697b9'
down_revision = 'ce8f2c2b92c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GoodCategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GoodCategory',
    sa.Column('fkGooodId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fkCategory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fkCategory'], ['Category.id'], name='GoodCategory_fkCategory_fkey'),
    sa.ForeignKeyConstraint(['fkGooodId'], ['Good.id'], name='GoodCategory_fkGooodId_fkey')
    )
    # ### end Alembic commands ###
