"""empty message

Revision ID: 930a2dd9a6e7
Revises: 6495dc8697b9
Create Date: 2020-03-02 22:08:14.871901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930a2dd9a6e7'
down_revision = '6495dc8697b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Busket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['Good.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Busket')
    # ### end Alembic commands ###
