"""empty message

Revision ID: ce8f2c2b92c4
Revises: 98cc4007dad5
Create Date: 2020-03-02 21:25:45.884620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8f2c2b92c4'
down_revision = '98cc4007dad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Good', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Good', 'Category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Good', type_='foreignkey')
    op.drop_column('Good', 'category_id')
    # ### end Alembic commands ###
